### PR TITLE
Stringrefs fixes

### PR DESCRIPTION
**Pull request by milipili**

### CODE REVIEW

**Comment by bborri** [comment]
The memory overhead estimation code seems very error-prone.
Did you unit test it ?

**Review by donho — APPROVED** [review]
I don't like m_* as variable member naming even it's conventional.
I would suggest you _* as variable member naming.

**Comment by bborri** [comment]
Also, have you considered the potential performance problems introduced by using std::deque instead of std::vector ?

**Review by donho — APPROVED** [review]

**Review by donho — APPROVED** [review]

**Review by donho — APPROVED** [review]

**Comment by milipili** [comment]
@bborri The memory overhead _estimation_ code does not intend to be accurate. It just now takes into consideration the internal structure of `std::unordered_map`. Anyway it will be fixed later by using our own memory allocator (provided by `nyallocator_t`, to restrict the memory usage when embedded in other applications), which will keep track of statistics.

@bborri About `std::deque`, the performance is comparable to `std::vector` in theory (slightly worse in theory). In practice, and as reported by `nanyc-unittest`, it performs slightly better (like said in commit message, `std::deque` is more efficient for large collections). Anyway the point here was to preserve references to elements when appending to the container, which `std::vector` does not guarantee contrary to `std::deque`

@donho Code review is not about personnal taste, but to enforce any current project's coding style, commit consistency, to make sure that the trade-offs are worth it or to eventually avoid poorly written code. In this case it is the project's coding style and has no place in code review (_but can be discussed on slack or somewhere else_). Additionally, using underscore as a prefix is a pretty bad idea. According to the C++ standards on reserved identifiers:
 * All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use.
 * All identifiers that begin with an underscore are always reserved for use as identifiers with file scope in both the ordinary and tag name spaces.  

So this convention already has a meaning. Let's not mess with it.

**Pull request merged**
